export class AudioEngine {
  constructor(){this.ctx=null;this.muted=false;this.musicStarted=false;this.musicBuffer=null;this.musicLoadPromise=null;this.musicSource=null;}
  async unlock(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.sfx=this.ctx.createGain();this.compressor=this.ctx.createDynamicsCompressor();this.master.gain.value=.9;this.music.gain.value=.2;this.sfx.gain.value=.72;this.compressor.threshold.value=-14;this.compressor.knee.value=10;this.compressor.ratio.value=7;this.compressor.attack.value=.003;this.compressor.release.value=.2;this.music.connect(this.master);this.sfx.connect(this.compressor).connect(this.master);this.master.connect(this.ctx.destination);this.makeNoise()}if(!this.musicLoadPromise)this.musicLoadPromise=fetch('assets/audio/space_flight.mp3').then(response=>response.arrayBuffer()).then(data=>this.ctx.decodeAudioData(data));this.musicBuffer=await this.musicLoadPromise;await this.ctx.resume();if(!this.musicStarted&&this.ctx.state==='running')this.startMusic();}
  makeNoise(){const length=this.ctx.sampleRate*1.5,data=new Float32Array(length);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);this.noise=this.ctx.createBuffer(1,length,this.ctx.sampleRate);this.noise.copyToChannel(data,0)}
  osc(destination,{freq,end=freq,duration=.1,type='sine',gain=.1,when=this.ctx.currentTime}){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,when);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),when+duration);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(gain,when+.008);g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g).connect(destination);o.start(when);o.stop(when+duration+.03);o.onended=()=>{o.disconnect();g.disconnect()}}
  noiseBurst(duration=.4,gain=.2,cutoff=1800){const now=this.ctx.currentTime,s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=this.noise;f.type='lowpass';f.frequency.setValueAtTime(cutoff,now);f.frequency.exponentialRampToValueAtTime(100,now+duration);g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);s.connect(f).connect(g).connect(this.sfx);s.start(now);s.stop(now+duration);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect()}}
  shoot(){if(!this.ctx||this.muted)return;const now=this.ctx.currentTime;this.osc(this.sfx,{freq:1250,end:95,duration:.38,type:'sawtooth',gain:.2,when:now});this.osc(this.sfx,{freq:105,end:38,duration:.55,type:'sine',gain:.5,when:now});this.osc(this.sfx,{freq:2100,end:380,duration:.13,type:'square',gain:.08,when:now});this.noiseBurst(.48,.34,2600)}
  hit(){if(!this.ctx||this.muted)return;this.noiseBurst(.8,.4,1400);this.osc(this.sfx,{freq:130,end:28,duration:.75,type:'sawtooth',gain:.34})}
  impact(){if(!this.ctx||this.muted)return;this.noiseBurst(.65,.25,700);this.osc(this.sfx,{freq:85,end:30,duration:.7,type:'triangle',gain:.3})}
  click(){if(!this.ctx||this.muted)return;this.osc(this.sfx,{freq:520,end:680,duration:.04,type:'sine',gain:.04})}
  startMusic(){this.musicStarted=true;this.musicSource=this.ctx.createBufferSource();this.musicSource.buffer=this.musicBuffer;this.musicSource.loop=true;this.musicSource.connect(this.music);this.music.gain.setValueAtTime(.0001,this.ctx.currentTime);this.music.gain.exponentialRampToValueAtTime(.2,this.ctx.currentTime+2.5);this.musicSource.start()}
  toggle(){this.muted=!this.muted;if(this.master)this.master.gain.setTargetAtTime(this.muted?0:.9,this.ctx.currentTime,.03);return this.muted;}
}
