import {C} from './config.js';
import {Viewport} from './core/viewport.js';
import {loadImages} from './core/assets.js';
import {AudioEngine} from './core/audio.js';
import {Input} from './core/input.js';
import {mulberry32} from './core/rng.js';
import {Starfield} from './entities/starfield.js';
import {ShootingStars} from './entities/shootingStars.js';
import {Fireball} from './entities/fireball.js';
import {Particles} from './fx/particles.js';

const canvas=document.querySelector('#game'),loading=document.querySelector('#loading'),loadingText=document.querySelector('#loadingText'),start=document.querySelector('#start');
const vp=new Viewport(canvas),ctx=vp.ctx,rng=mulberry32(),audio=new AudioEngine();
let state='LOADING',images,score=0,angle=0,bullets=[],cooldown=0,recoil=0,flash=0,shake=0,shock=null,last=performance.now(),paused=false,nextMeteor=.15,sequenceStep=0,sequenceEdges=buildMeteorSequence(),tutorialTime=0,tutorialFired=false,tutorialPlayed=false;
const stars=new Starfield(rng),shooters=new ShootingStars(rng),meteors=[],fx=new Particles();
const manifest={screen:'assets/images/screen.png',barrel:'assets/images/turret_barrel.png',base:'assets/images/turret_base.png',fire:'assets/images/btn_fire.png',meteor:'assets/images/fireball_sheet.png',hand:'assets/images/hand_nudge.webp'};

function muzzle(){const a=angle*Math.PI/180;return{x:C.PIVOT_X+Math.sin(a)*C.BARREL_LEN,y:C.PIVOT_Y-Math.cos(a)*C.BARREL_LEN,fx:Math.sin(a),fy:-Math.cos(a)}}
function fire(tutorialDemo=false){if((state!=='PLAYING'&&!(tutorialDemo&&state==='TUTORIAL'))||cooldown>0||bullets.length>=C.MAX_BULLETS)return;const m=muzzle();bullets.push({x:m.x,y:m.y,px:m.x,py:m.y,vx:m.fx*C.BULLET_SPEED,vy:m.fy*C.BULLET_SPEED});fx.emit({x:m.x,y:m.y,s0:80,s1:320,life:.25,r:3,color:'#9ffcff'},10);cooldown=C.BULLET_COOLDOWN;recoil=1;if(state==='PLAYING')audio.shoot()}
function aimAt(p){if(state!=='PLAYING')return;const dx=p.x-C.PIVOT_X,dy=C.PIVOT_Y-p.y;angle=Math.max(-C.AIM_CLAMP,Math.min(C.AIM_CLAMP,Math.atan2(dx,dy)*180/Math.PI))}
const input=new Input(canvas,vp,fire,()=>{if(state==='PLAYING')audio.toggle()},()=>{if(state==='PLAYING')audio.click()},aimAt);
function segmentHit(b,f,r){const dx=b.x-b.px,dy=b.y-b.py,l2=dx*dx+dy*dy;if(!l2)return Math.hypot(b.x-f.x,b.y-f.y)<r;const t=Math.max(0,Math.min(1,((f.x-b.px)*dx+(f.y-b.py)*dy)/l2)),x=b.px+t*dx,y=b.py+t*dy;return Math.hypot(x-f.x,y-f.y)<r}
function explode(meteor){const x=meteor.x,y=meteor.y;meteor.alive=false;fx.emit({x,y,s0:200,s1:600,life:.85,r:8,color:'#ff9500'},44);flash=.09;shake=.18;shock={x,y,t:0};score++;audio.hit()}
function miss(meteor){const x=meteor.x,y=Math.min(meteor.y,C.HUD_Y);meteor.alive=false;fx.emit({x,y,s0:40,s1:120,life:1.3,r:24},32,'smoke');fx.emit({x,y,s0:100,s1:260,life:.55,r:4,color:'#ba9ec9'},16);shake=.13;audio.impact()}
function exitMeteor(meteor){meteor.alive=false}
function buildMeteorSequence(){const first=(rng()*3)|0,second=first===1?2:first===2?1:(rng()<.5?1:2),third=[0,1,2].find(edge=>edge!==first&&edge!==second),fourth=third===0?first:0;return[first,second,third,fourth]}
function spawnMeteor(){const meteor=new Fireball(rng),colors=['normal','purple','pink','green'];meteor.spawn(sequenceEdges[sequenceStep],colors[sequenceStep]);meteors.push(meteor);sequenceStep++;if(sequenceStep===4){sequenceStep=0;sequenceEdges=buildMeteorSequence()}nextMeteor=1}
function startTutorial(){if(tutorialPlayed)return;tutorialPlayed=true;state='TUTORIAL';tutorialTime=0;tutorialFired=false;angle=-90;meteors.length=0;bullets=[];start.classList.add('hidden');audio.unlock().catch(()=>{});const meteor=new Fireball(rng);meteor.spawn(0);meteor.x=1160;meteor.y=250;meteor.age=3;meteor.entered=true;meteor.chainStarted=true;const dx=C.IMPACT_X-meteor.x,dy=C.IMPACT_Y-meteor.y,d=Math.hypot(dx,dy);meteor.vx=dx/d*48;meteor.vy=dy/d*48;meteors.push(meteor)}
function update(dt){stars.update(dt);shooters.update(dt);fx.update(dt);cooldown=Math.max(0,cooldown-dt);recoil=Math.max(0,recoil-dt/0.12);flash=Math.max(0,flash-dt);shake=Math.max(0,shake-dt);if(shock){shock.t+=dt;if(shock.t>.35)shock=null}if(state!=='PLAYING'&&state!=='TUTORIAL')return;
  angle=Math.max(-C.AIM_CLAMP,Math.min(C.AIM_CLAMP,angle+((input.right?1:0)-(input.left?1:0))*C.AIM_SPEED*dt));
  if(state==='TUTORIAL'){tutorialTime+=dt;const meteor=meteors.find(m=>m.alive);if(tutorialTime<3.4)angle=-90+180*(.5-.5*Math.cos(Math.PI*tutorialTime/3.4));else if(meteor){const dx=meteor.x-C.PIVOT_X,dy=C.PIVOT_Y-meteor.y;angle=Math.max(-90,Math.min(90,Math.atan2(dx,dy)*180/Math.PI))}if(tutorialTime>=7.2&&!tutorialFired){tutorialFired=true;fire(true)}if(tutorialTime>=10){state='READY';meteors.length=0;bullets=[];score=0;angle=0;input.clear();start.classList.remove('hidden')}}
  if(state==='PLAYING'){nextMeteor-=dt;const active=meteors.filter(m=>m.alive);if(!active.length&&nextMeteor<=0)spawnMeteor();else if(active.length<4){const trigger=active.find(m=>m.entered&&!m.chainStarted);if(trigger){trigger.chainStarted=true;spawnMeteor()}}}
  for(const meteor of meteors){const result=meteor.update(dt);if(result==='miss')miss(meteor);else if(result==='exit')exitMeteor(meteor)}
  for(const b of bullets){b.px=b.x;b.py=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;for(const meteor of meteors)if(!b.dead&&meteor.alive&&segmentHit(b,meteor,C.FIREBALL_HIT_RADIUS+C.BULLET_RADIUS)){b.dead=true;explode(meteor)}}
  for(let i=meteors.length-1;i>=0;i--)if(!meteors[i].alive)meteors.splice(i,1);
  bullets=bullets.filter(b=>!b.dead&&b.x>-100&&b.x<C.W+100&&b.y>-100&&b.y<C.H+100);
}
function drawBullet(b){ctx.save();ctx.globalCompositeOperation='lighter';const n=Math.hypot(b.vx,b.vy),tx=b.x-b.vx/n*50,ty=b.y-b.vy/n*50,g=ctx.createLinearGradient(tx,ty,b.x,b.y);g.addColorStop(0,'transparent');g.addColorStop(1,'#00d4ff');ctx.strokeStyle=g;ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x,b.y,6,0,7);ctx.fill();ctx.restore()}
function pill(x,y,w,h){ctx.beginPath();ctx.roundRect(x,y,w,h,h/2);ctx.fill()}
function drawHand(x,y,pulse=0){if(!images?.hand)return;ctx.save();ctx.translate(x,y);const bob=Math.sin(performance.now()/180)*5,scale=1+Math.sin(performance.now()/210)*.025;ctx.scale(scale,scale);ctx.shadowColor='#00d4ff';ctx.shadowBlur=18;ctx.drawImage(images.hand,-42,-8+bob,104,148);if(pulse){ctx.globalAlpha=.45+.25*Math.sin(pulse*6);ctx.strokeStyle='#65ecff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,54,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawTutorial(t){const phase=tutorialTime<3.4?0:tutorialTime<6.8?1:2,remaining=Math.max(0,Math.ceil(10-tutorialTime)),messages=[['AIM RANGE  •  0° — 180°','Watch how the missile moves across the full aiming range'],['AIM AT THE INCOMING FIRE','Line up the missile with the moving target'],['BLAST WHEN ALIGNED','Fire when the missile is aimed correctly']],msg=messages[phase];ctx.save();ctx.fillStyle='#07102088';ctx.fillRect(0,0,C.W,310);ctx.textAlign='center';ctx.shadowColor='#00d4ff';ctx.shadowBlur=20;ctx.fillStyle='#fff';ctx.font='900 38px system-ui';ctx.fillText(msg[0],C.W/2,100);ctx.shadowBlur=7;ctx.fillStyle='#a6efff';ctx.font='600 21px system-ui';ctx.fillText(msg[1],C.W/2,145);ctx.fillStyle='#ffffffdd';ctx.font='700 18px system-ui';ctx.fillText(`TUTORIAL ENDS IN ${remaining}`,C.W/2,190);ctx.fillStyle='#17284d';pill(C.W/2-250,220,500,11);ctx.fillStyle='#00d4ff';pill(C.W/2-250,220,500*(tutorialTime/10),11);ctx.restore();if(phase===0){const a=angle*Math.PI/180,nudge=Math.sin(t*5)*18;drawHand(C.PIVOT_X+Math.sin(a)*310+nudge*Math.cos(a),C.PIVOT_Y-Math.cos(a)*310+nudge*Math.sin(a))}else if(phase===1){const a=angle*Math.PI/180;drawHand(C.PIVOT_X+Math.sin(a)*300,C.PIVOT_Y-Math.cos(a)*300)}else drawHand(C.FIRE.x,C.FIRE.y-62,t)}
function draw(t){const sx=shake?((Math.random()-.5)*12*shake/.18):0,sy=shake?((Math.random()-.5)*12*shake/.18):0;vp.begin(sx,sy);if(images?.screen)ctx.drawImage(images.screen,0,0,C.W,C.HUD_Y,0,0,C.W,C.H);stars.draw(ctx,t);shooters.draw(ctx);for(const meteor of meteors)meteor.draw(ctx,images?.meteor);for(const b of bullets)drawBullet(b);fx.draw(ctx);
  if(shock){const q=shock.t/.35,e=1-Math.pow(1-q,3);ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle=`rgba(255,180,80,${1-q})`;ctx.lineWidth=12*(1-q);ctx.beginPath();ctx.arc(shock.x,shock.y,20+200*e,0,7);ctx.stroke();ctx.restore()}
  if(images?.barrel){ctx.save();ctx.translate(C.PIVOT_X,C.PIVOT_Y);ctx.rotate(angle*Math.PI/180);ctx.translate(0,recoil*9);ctx.drawImage(images.barrel,-C.PIVOT_X,-C.PIVOT_Y,C.W,C.H);ctx.restore()}if(images?.base)ctx.drawImage(images.base,0,0,C.W,C.H);if(images?.fire)ctx.drawImage(images.fire,0,0,C.W,C.H);
  ctx.save();ctx.fillStyle='#00000055';pill(48,42,245,66);ctx.fillStyle='#fff';ctx.shadowColor='#00d4ff';ctx.shadowBlur=16;ctx.font='800 32px system-ui';ctx.fillText(`SCORE  ${String(score).padStart(3,'0')}`,72,86);ctx.shadowBlur=10;ctx.textAlign='center';ctx.font='700 42px system-ui';ctx.fillText(audio.muted?'×':'♪',1840,86);ctx.font='900 20px system-ui';ctx.letterSpacing='3px';ctx.fillText('BLAST',C.FIRE.x,C.FIRE.y+8);ctx.restore();
  if(meteors.some(m=>m.alive)){const degrees=Math.round(angle+90);ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#8defff';ctx.shadowColor='#00d4ff';ctx.shadowBlur=18;ctx.font='700 18px system-ui';ctx.fillText('FIRING ANGLE',C.W/2,C.H/2-28);ctx.fillStyle='#fff';ctx.shadowBlur=24;ctx.font='900 48px system-ui';ctx.fillText(`${degrees}°`,C.W/2,C.H/2+18);ctx.restore()}
  if(state==='TUTORIAL')drawTutorial(t);
  if(flash){ctx.save();ctx.globalCompositeOperation='lighter';ctx.fillStyle=`rgba(255,180,80,${.35*flash/.09})`;ctx.fillRect(0,0,C.W,C.H);ctx.restore()}}
function loop(now){const dt=Math.min(C.DT_MAX,(now-last)/1000||0);last=now;if(!paused)update(dt);draw(now/1000);requestAnimationFrame(loop)}
document.addEventListener('visibilitychange',async()=>{paused=document.hidden;input.clear();if(audio.ctx){if(paused)await audio.ctx.suspend();else if(state==='PLAYING'||state==='TUTORIAL')await audio.ctx.resume()}last=performance.now()});
start.addEventListener('pointerdown',async e=>{if(state!=='READY')return;e.preventDefault();await audio.unlock();state='PLAYING';start.classList.add('hidden');sequenceStep=0;sequenceEdges=buildMeteorSequence();nextMeteor=.15});
window.__DEBUG={get state(){return state},get angle(){return angle},get score(){return score},get tutorialTime(){return tutorialTime},skipTutorial:()=>{if(state==='TUTORIAL'){state='READY';meteors.length=0;bullets=[];angle=0;start.classList.remove('hidden')}},entityCounts:()=>({bullets:bullets.length,particles:fx.count(),fireball:meteors.filter(m=>m.alive).length}),spawn:(edge=0)=>{const m=new Fireball(rng);m.spawn(edge);meteors.push(m)},fire,forceHit:()=>{if(!meteors.length)spawnMeteor();explode(meteors[0])},forceMiss:()=>{if(!meteors.length)spawnMeteor();miss(meteors[0])}};
images=await loadImages(manifest,p=>loadingText.textContent=`LOADING ${Math.round(p*100)}%`);loading.classList.add('hidden');startTutorial();requestAnimationFrame(loop);
